### ISSUE TITLE
Memory map for segment

### ISSUE THREAD

**Issue by tekjar** [liftbridge-io/liftbridge#178]
Hi. I [see](https://github.com/liftbridge-io/liftbridge/blob/master/server/commitlog/segment.go#L51-L53) that segment uses normal buffered io where as index [uses](https://github.com/liftbridge-io/liftbridge/blob/master/server/commitlog/index.go#L29) mmap. Any disadvantage in using mmap for segment as well?

**Comment by tylertreat** [comment]
The reason we mmap indexes is because mmap is particularly good for randomly accessing small pieces of a large file, but it's less good for reading large amounts of data. This is because mmap page faults when the contents being looked up are not in memory.

In contrast, normal read() and write() syscalls are super efficient when it comes to linear I/O and they typically don't have the same page fault issues as mmap. This is also better for multiple readers/writers, which is the case for log segments in Liftbridge. Here's a more [in-depth explanation](https://www.quora.com/How-is-a-mmaped-file-I-O-different-from-a-regular-file-I-O-with-regard-to-the-kernel).

**Comment by tekjar** [comment]
Ahh thanks!! That's helpful
