### ISSUE TITLE
Message Queueing

### ISSUE THREAD

**Issue by benstadin** [liftbridge-io/liftbridge#199]
Liftbridge looks very interesting. I have a use case where I need a simple message queueing capability (I have just one publisher to a stream of ordered data records, and one consumer filtering the stream and writing data to a database). 

Is queuing on the roadmap? Is it possible to implement a simple queueing scheme in a pragmatic way for mentioned use case?

**Comment by tylertreat** [comment]
I'd like to learn more about your use case to understand how you might solve it with Liftbridge or what capabilities Liftbridge might need to satisfy it (and related use cases).

Typically with queueing I think of "competing consumer" type semantics. That is, you have a group of consumers which messages from a queue are distributed to. In your case, since you have just a single consumer, I'm not sure I quite understand what queueing behavior you're looking for. Is it just to "remove" a message from the stream once it's processed? If so, this should be solvable with Liftbridge by tracking the consumer's position in the stream (there are plans to implement this tracking in the client so you don't have to manage this bookkeeping).

Keep in mind that with _multiple_ competing consumers, you lose strict ordering of messages since consumers will process messages out of order. That is one of the trade-offs of having multiple consumers of the same stream.

**Comment by benstadin** [comment]
For a background it's geo data processing, e.g. collision detection for moving things (autonomous vehicles, cars, but also workers getting too close to another for COVID analysis and company manufacturing process improvement in that regard).

I have an application where each instance of it runs on-site at a company's location (at the moment exactly one instance per location). On a company site there is exactly one active instance of that application (instances cannot be replicated by simple means due to spatial indexing complexities). 

The local (e.g. per company site) instances filter some some raw data which multiple systems publish to it at that location (in various ways, websocket, mqtt, rest). All data will be transformed (space and time analysis for a certain timeframe), filtered and then a limited set of that data will be published to a distributed database. The transformed and filtered data is then accessible globally via a cloud service. Typically, only about 1/1000 data records of the original raw data actually go into the global distributed db. 

Now I need to implement failover and automated recovery for those local on-site instances of my application, so that another instances can take over at any time. The challenge is that the passive-standby instance(s) need to be in sync with the transformed data being pre-processed by the active instance, with the goal to not loose data which has been transformed but not yet published to the distributed db. 

For this I thought about putting a high performance, replicating streaming server in between. The active instance of my application will be the single publisher to the replicated stream, and the passive instances will consume the stream to stay in sync. On failover one of the passive instances will become active, take over data transformation for all raw data publishers at that location, and will become the single publisher to the replicated stream.

This is all theory at the moment, still thinking about the best architecture.

**Comment by tylertreat** [comment]
Just spitballing some ideas...

Would it be feasible to separate the global database publisher and put a stream in front of it? My thought is you could have the active instance perform the data transformations then write the results to a stream. The publisher would then consume that stream, publish the filtered results to the database, and track its position in the stream. This way, you know exactly where to pick up publishing in the event of a failure and can separate that from the data preprocessing since it sounds like that might be a more stateful process. You could also potentially use this stream to do the replication to the standby instances.

Another thought is to put a stream in _front_ of the active/passive instances. You could have an adapter of some sort that can bridge between different publishers (websocket, mqtt, rest, etc.) to first write to the stream if necessary. This would basically act as a write-ahead log. A benefit of this would be the raw data publishers wouldn't be disrupted during a failover of the active instance. Active/passive instances would inherently stay in sync by consuming the same stream. The trick here is knowing where to begin publishing to the database in the event of a failover.

In either case, it seems feasible without traditional queueing semantics since it sounds like it's mostly a matter of tracking position in a stream(s).

**Comment by tylertreat** [comment]
Closing this for now. Feel free to re-open.
