### ISSUE TITLE
Encryption at rest

### ISSUE THREAD

**Issue by tylertreat** [liftbridge-io/liftbridge#217]
Support encryption of stream data stored on disk. Determine whether this should also include encryption of metadata (i.e. Raft log).

**Comment by LaPetiteSouris** [comment]
Just start working on this feature. A few thoughts I would like to share 

- For encryption of stream. would it be too much to encrypt both log file and index files ? Would it suffice to encrypt only the data-at-rest ( log file ) ?

- I think it makes sense to make this feature opt-in per stream level. Make sense ?

- I am thinking about the encryption key. The basic solution would be to keep it on server side as environment variable. However, more advanced storage solution can be planned, like [Hashicorp Vault](https://www.vaultproject.io) . or other secret manager solution.

- It would be hard to manage encryption key change. I.g: One would have to carry out decryption of everything existing and re-encrypt it with a new key, which I think unmaintainable. It means effectively, encryption key, once set, cannot be changed without breaking existing data.

- For the first version, I would suggest to have one single encryption key per server. I.e: all streams are encrypted with the same key. Not a security expert , I cannot say if this is good or bad, it's just that from maintenance and implementation view point, it would be hard otherwise.

**Comment by tylertreat** [comment]
> For encryption of streams, would it be too much to encrypt both log file and index files ? Would it suffice to encrypt only the data-at-rest ( log file ) ?

I believe only log file is necessary since index files merely contain pointers into the log files.

> I think this feature shall be opt-in per stream level. Make sense ?

I think this is correct.

> I am thinking about the encryption key. The basic solution would be to keep it on server side as environment variable. However, more advanced storage solution can be planned, like Hashicorp Vault or other secret manager solution.

Yes, I think a simple new config that is a path to an encryption key to start with an eye towards integrations in the future makes sense.

> It would be hard to manage encryption key change. I.e: One would have to carry out decryption of everything existing and re-encrypt it with a new key, which I think unmaintainable. It means effectively, encryption key, once set, cannot be changed without breaking existing data.

One thought here is since we will likely provide support for other KMS systems in the future (e.g. Vault), we could take an [envelope encryption](https://cloud.google.com/kms/docs/envelope-encryption) approach. This is how cloud providers allow rotating encryption keys for databases and such by wrapping the _data_ encryption key with a _key_ encryption key. This doesn't provide much value to start when the keys are all located on the Liftbridge server, but with the addition of an external KMS it might. Something to think about.

> For the first version, I would suggest to have one single encryption key per server. I.e: all streams are encrypted with the same key. Not a security expert , I cannot say if this is good or bad, it's just that from maintenance and implementation view point, it would be hard otherwise.

I think this is a reasonable assumption, at least to start.

**Comment by LaPetiteSouris** [comment]
> > It would be hard to manage encryption key change. I.e: One would have to carry out decryption of everything existing and re-encrypt it with a new key, which I think unmaintainable. It means effectively, encryption key, once set, cannot be changed without breaking existing data.
> 
> One thought here is since we will likely provide support for other KMS systems in the future (e.g. Vault), we could take an [envelope encryption](https://cloud.google.com/kms/docs/envelope-encryption) approach. This is how cloud providers allow rotating encryption keys for databases and such by wrapping the _data_ encryption key with a _key_ encryption key. This doesn't provide much value to start when the keys are all located on the Liftbridge server, but with the addition of an external KMS it might. Something to think about.
> 

The envelope encryption is amazing. I did not know that technique. Basically, storing an encrypted key along with the data solves nicely the problem about key changes. 

That would make the implementation slightly more complex, but I think it worths the effort. 

I will try to go forward with implementation then.

**Comment by tylertreat** [comment]
> I think this feature shall be opt-in per stream level. Make sense ?

Also, one more note on this. I think we should follow the pattern of allowing this to be set globally and overridden on a per stream basis.

**Comment by LaPetiteSouris** [comment]
> > I think this feature shall be opt-in per stream level. Make sense ?
> 
> Also, one more note on this. I think we should follow the pattern of allowing this to be set globally and overridden on a per stream basis.

Agreed. By default it would be deactivated. 

Nice to have: a cluster set up to measure performance when encryption is enabled and disabled. I can do it locally, but what metrics should be defined in such case ?

**Comment by tylertreat** [comment]
> Nice to have: a cluster set up to measure performance when encryption is enabled and disabled. I can do it locally, but what metrics should be defined in such case ?

Could use a Go benchmark to test performance changes at the commitlog level. Agree it would be nice to have a large-scale, end-to-end benchmarking framework though.
