### ISSUE TITLE
backpressure?

### ISSUE THREAD

**Issue by glycerine** [liftbridge-io/liftbridge#44]
Hi Tyler! Cool looking project!

A problem with basic nats is that it is very easy for a fast producer to overrun even a lone consumer. There's no backpressure built in. Consumers get cut off for being slow.

Kafka gives backpressure. So I wonder if Liftbridge will as well--so as to remedy this problem with basic nats?

Jason

**Comment by tylertreat** [comment]
Hey Jason,

To my knowledge, Kafka provides a couple mechanisms. There are publisher
acks (which is really more a mechanism to guarantee delivery) and quotas
(which is a way to enforce rate limits on publishers). Am I missing
anything there?

Currently, Liftbridge only has publisher acks (which work very similarly to
Kafka). I am open to ideas here since I agree there needs to be a way to
throttle "bad actors," and Liftbridge is very much inspired by Kafka's
architecture.

**Comment by glycerine** [comment]
> Am I missing anything here?

I was thinking of the basic design in Kafka where the producer's every write is stored on disk (after being sent over TCP) every time, without a high water mark, without any code that deliberately drops messages. So TCP's backpressure applies here.

This isn't from reading Kafka's source, but rather my reading of the design. e.g. https://svn.apache.org/repos/asf/kafka/site/082/design.html
~~~
4.5 The Consumer
The Kafka consumer works by issuing "fetch" requests to the 
brokers leading the partitions it wants to consume. The consumer 
specifies its offset in the log with each request and receives back 
a chunk of log beginning from that position. The consumer thus 
has significant control over this position and can rewind it to re-consume data if need be.

Push vs. pull

An initial question we considered is whether consumers should 
pull data from brokers or brokers should push data to the consumer. 
In this respect Kafka follows a more traditional design, shared by 
most messaging systems, where data is pushed to the broker 
from the producer and pulled from the broker by the consumer. 
Some logging-centric systems, such as Scribe and Apache Flume follow a very different push based path where data is pushed downstream. There are pros and 
cons to both approaches. However a push-based system has 
difficulty dealing with diverse consumers as the broker controls the 
rate at which data is transferred. The goal is generally for the consumer 
to be able to consume at the maximum possible rate; unfortunately in a 
push system this means the consumer tends to be overwhelmed when its rate of consumption falls below the rate of production (a denial of service attack, in essence). 
A pull-based system has the nicer property that the consumer simply 
falls behind and catches up when it can. This can be mitigated with 
some kind of backoff protocol by which the consumer can indicate it is 
overwhelmed, but getting the rate of transfer to fully utilize (but never 
over-utilize) the consumer is trickier than it seems. Previous attempts 
at building systems in this fashion led us to go with a more traditional pull model.

Another advantage of a pull-based system is that it lends itself 
to aggressive batching of data sent to the consumer. A push-
based system must choose to either send a request immediately 
or accumulate more data and then send it later without knowledge 
of whether the downstream consumer will be able to immediately 
process it. If tuned for low latency this will result in sending a 
single message at a time only for the transfer to end up being 
buffered anyway, which is wasteful. A pull-based design fixes 
this as the consumer always pulls all available messages after 
its current position in the log (or up to some configurable max size). 
So one gets optimal batching without introducing unnecessary latency.

The deficiency of a naive pull-based system is that if the broker 
has no data the consumer may end up polling in a tight loop, 
effectively busy-waiting for data to arrive. To avoid this we 
have parameters in our pull request that allow the consumer 
request to block in a "long poll" waiting until data arrives (and 
optionally waiting until a given number of bytes is available to 
ensure large transfer sizes).
~~~

**Comment by tylertreat** [comment]
Right, so Liftbridge also writes every message to a write-ahead log. The
caveat with Liftbridge is it is a durable log extension for NATS. As such,
it's just like any other NATS consumer and is susceptible to the same
slower consumer problems in NATS, though there are some tricks to minimize
that problem. Still, it can be a problem if you structure your streams in
such a way where load is not evenly distributed, i.e. a single stream with
a massive amount of load could potentially cause a disconnect from NATS.
This problem exists in NATS Streaming today as well.

Normally what you would do to mitigate this is have some sort of rate
limiting capabilities/backpressure. Kafka has the benefit of being straight
TCP, but it also does this with quotas. With Liftbridge, it's a bit tricky
since it's just consuming NATS. Technically, the disconnect doesn't violate
any guarantees since to ensure guaranteed delivery, a publisher needs to
wait on the ack. If it disconnects because of slow consumer, no ack. You
could implement identity/quotas in the higher level Liftbridge envelope
protocol, but that doesn't account for messages published to NATS which are
not using envelopes. This is one unfortunate part of the NATS protocol not
being extensible. Anyway, I haven't thought that far ahead yet, but would
love to hear any ideas.

**Comment by glycerine** [comment]
> but would love to hear any ideas.

Yeah. I don't know the answer. It does seem like a basic flaw in the nats approach. I did implement the sliding-window protocol at one point on top of nats to fix this for a particular use case.

https://github.com/glycerine/go-sliding-window

**Comment by glycerine** [comment]
These days I've been using gRPC or https://github.com/smallnest/rpcx . Both have been superior to NATS for applications under load, as they don't drop the backpressure. I guess its a clever marketing gimic to claim this as a feature (always on! dial-tone!) but in reality it means I cannot rely on nats if the load increases.

**Comment by tylertreat** [comment]
Closing this for now as there are no plans to address this at the moment.
