### ISSUE TITLE
Will be multi-language? Is already?

### ISSUE THREAD

**Issue by paul-hammant** [liftbridge-io/liftbridge#5]
Java, Python, Ruby, NodeJS specifically?

If yes, example code?

**Comment by tylertreat** [comment]
Yes, Liftbridge has a very simple [gRPC API](https://github.com/liftbridge-io/liftbridge-grpc). This allows you to generate clients for all of those languages. [go-liftbridge](https://github.com/liftbridge-io/go-liftbridge) uses the generated Go client to provide a slightly higher level API. The goal would be to provide similar high-level API wrappers for other languages, but there's a lot of other work that needs to be done still. If you have a particular language in mind, I would be happy to help guide you. Otherwise it will be a while before I can get to them.

**Comment by tylertreat** [comment]
And when I say Liftbridge has a simple API, [I do mean simple](https://github.com/liftbridge-io/liftbridge-grpc/blob/d658c291552f32ce810995c5e9dca9862ecc44da/api.proto#L104-L120). ;)

**Comment by paul-hammant** [comment]
I'm backlogged too. Just trying to help crystallize your FAQs.  Incidentally, I parallelize my work by putting fixed price contracts on UpWork. Like $30.
